const titleV = document.getElementById("titleV");
const data = document.getElementById("data");
const left = document.getElementById("left");
const right = document.getElementById("right");
const start = document.getElementById("start");
const numerator = document.getElementById("numerator");
const denominator = document.getElementById("denominator");

let URLlist = [
  "https://www.ap-siken.com/kakomon/28_aki/q13.html",
  "https://www.ap-siken.com/kakomon/29_aki/q26.html",
  "https://www.ap-siken.com/kakomon/21_aki/q14.html",
  "https://www.ap-siken.com/kakomon/21_haru/q31.html",
  "https://www.ap-siken.com/kakomon/19_haru/q31.html",
  "https://www.ap-siken.com/kakomon/27_aki/q13.html",
  "https://www.ap-siken.com/kakomon/22_haru/q14.html",
  "https://www.ap-siken.com/kakomon/02_menjo/q25.html",
  "https://www.ap-siken.com/kakomon/27_haru/q27.html",
  "https://www.ap-siken.com/kakomon/30_haru/q35.html",
  "https://www.fe-siken.com/kakomon/24_haru/q09.html",
  "https://www.ap-siken.com/kakomon/18_aki/q38.html",
  "https://www.ap-siken.com/kakomon/19_haru/q38.html",
  "https://www.ap-siken.com/kakomon/30_haru/q13.html",
  "https://www.ap-siken.com/kakomon/28_aki/q46.html",
  "https://www.ap-siken.com/kakomon/25_aki/q13.html",
  "https://www.ap-siken.com/kakomon/25_haru/q14.html",
  "https://www.ap-siken.com/kakomon/03_menjo/q15.html",
  "https://www.ap-siken.com/kakomon/27_aki/q56.html",
  "https://www.ap-siken.com/kakomon/26_haru/q15.html",
  "https://www.ap-siken.com/kakomon/23_aki/q17.html",
  "https://www.ap-siken.com/kakomon/18_haru/q33.html",
  "https://www.ap-siken.com/kakomon/23_haru/q15.html",
  "https://www.ap-siken.com/kakomon/16_aki/q33.html",
  "https://www.ap-siken.com/kakomon/31_haru/q13.html",
  "https://www.ap-siken.com/kakomon/29_aki/q13.html",
  "https://www.ap-siken.com/kakomon/20_haru/q31.html",
  "https://www.ap-siken.com/kakomon/30_haru/q14.html",
  "https://www.ap-siken.com/kakomon/28_aki/q14.html",
  "https://www.ap-siken.com/kakomon/21_aki/q15.html",
  "https://www.ap-siken.com/kakomon/26_aki/q13.html",
  "https://www.ap-siken.com/kakomon/19_aki/q35.html",
  "https://www.ap-siken.com/kakomon/29_aki/q14.html",
  "https://www.ap-siken.com/kakomon/24_haru/q15.html",
  "https://www.ap-siken.com/kakomon/g_moto_aki/q72.html",
  "https://www.ap-siken.com/kakomon/28_haru/q41.html",
  "https://www.ap-siken.com/kakomon/24_aki/q63.html",
  "https://www.ap-siken.com/kakomon/29_haru/q63.html",
  "https://www.ap-siken.com/kakomon/23_aki/q16.html",
  "https://www.ap-siken.com/kakomon/28_aki/q14.html",
  "https://www.ap-siken.com/kakomon/15_haru/q37.html",
  "https://www.ap-siken.com/kakomon/20_aki/q31.html",
  "https://www.ap-siken.com/kakomon/05_menjo/q04.html",
  "https://www.ap-siken.com/kakomon/g_moto_aki/q15.html",
  "https://www.ap-siken.com/kakomon/29_aki/q12.html",
  "https://www.ap-siken.com/kakomon/29_haru/q11.html",
  "https://www.ap-siken.com/kakomon/28_aki/q12.html",
  "https://www.ap-siken.com/kakomon/21_haru/q13.html",
  "https://www.ap-siken.com/kakomon/16_haru/q23.html",
  "https://www.ap-siken.com/kakomon/15_haru/q26.html",
  "https://www.ap-siken.com/kakomon/22_aki/q15.html",
  "https://www.ap-siken.com/kakomon/19_haru/q32.html",
  "https://www.ap-siken.com/kakomon/17_haru/q24.html",
  "https://www.ap-siken.com/kakomon/22_haru/q34.html",
  "https://www.ap-siken.com/kakomon/21_aki/q17.html",
  "https://www.ap-siken.com/kakomon/26_haru/q14.html",
  "https://www.ap-siken.com/kakomon/25_haru/q16.html",
  "https://www.ap-siken.com/kakomon/20_aki/q33.html",
  "https://www.ap-siken.com/kakomon/25_aki/q09.html",
  "https://www.ap-siken.com/kakomon/23_haru/q19.html",
  "https://www.ap-siken.com/kakomon/30_haru/q15.html",
  "https://www.ap-siken.com/kakomon/29_haru/q12.html",
  "https://www.ap-siken.com/kakomon/29_haru/q13.html",
  "https://www.ap-siken.com/kakomon/25_aki/q16.html",
  "https://www.ap-siken.com/kakomon/19_aki/q32.html",
  "https://www.ap-siken.com/kakomon/27_haru/q16.html",
  "https://www.ap-siken.com/kakomon/20_haru/q34.html",
  "https://www.ap-siken.com/kakomon/27_aki/q14.html",
  "https://www.ap-siken.com/kakomon/25_aki/q14.html",
  "https://www.ap-siken.com/kakomon/20_aki/q34.html",
  "https://www.ap-siken.com/kakomon/16_aki/q38.html",
  "https://www.ap-siken.com/kakomon/07_menjo/q04.html",
  "https://www.ap-siken.com/kakomon/29_aki/q15.html",
  "https://www.ap-siken.com/kakomon/g_moto_aki/q16.html",
  "https://www.ap-siken.com/kakomon/31_haru/q14.html",
  "https://www.ap-siken.com/kakomon/30_aki/q15.html",
  "https://www.ap-siken.com/kakomon/29_haru/q14.html",
  "https://www.ap-siken.com/kakomon/28_haru/q15.html",
  "https://www.ap-siken.com/kakomon/27_haru/q15.html",
  "https://www.ap-siken.com/kakomon/26_aki/q14.html",
  "https://www.ap-siken.com/kakomon/24_aki/q15.html",
  "https://www.ap-siken.com/kakomon/24_haru/q17.html",
  "https://www.ap-siken.com/kakomon/23_haru/q16.html",
  "https://www.ap-siken.com/kakomon/22_aki/q19.html",
  "https://www.ap-siken.com/kakomon/22_haru/q16.html",
  "https://www.ap-siken.com/kakomon/21_aki/q16.html",
  "https://www.ap-siken.com/kakomon/21_haru/q56.html",
  "https://www.ap-siken.com/kakomon/18_aki/q33.html",
  "https://www.ap-siken.com/kakomon/26_aki/q15.html",
  "https://www.ap-siken.com/kakomon/20_haru/q33.html",
  "https://www.ap-siken.com/kakomon/27_haru/q13.html"
];
let titleList = [
  "3層クライアントサーバシステム構成",
  "クライアントサーバシステム",
  "クライアントサーバシステムの特徴",
  "クライアントとサーバ間の通信負荷",
  "クライアントサーバシステムの特徴",
  "3層クライアントサーバシステムの特徴",
  "3層クライアントサーバシステム",
  "ストアドプロシジャーの利点",
  "ストアドプロシージャの利用",
  "Web サーバと外部プログラムの連携",
  "Web サーバで動作するプログラム",
  "Web アプリケーションサーバの機能",
  "アプリケーションサーバ",
  "フォールトトレラントシステム",
  "フールプルーフに該当するもの",
  "フォールトトレラントシステム",
  "フォールトトレラントシステムの説明",
  "フェールセーフの考え方",
  "フェールセーフについて",
  "フェールセーフ設計の考え方",
  "フェールソフトの例",
  "フェールセーフ",
  "密結合マルチプロセッサシステム",
  "マルチプロセッサ環境の OS",
  "デュアルシステムの説明",
  "デュアルシステムに関する記述",
  "並列処理システムの説明",
  "並列処理システム",
  "ホットスタンバイ形式によるクラスタ構成",
  "ホットスタンバイ方式に関する記述",
  "ホットサイトに関する記述",
  "バックアップサイト",
  "クラウドサービスへ移行",
  "クラウドコンピューティングの説明",
  "クラウドファンディングの説明",
  "SaaS を利用するときのセキュリティ管理",
  "SaaS の説明",
  "ホスティングサービスの特徴はどれか",
  "シンクライアントシステムの特徴",
  "ホットスタンバイ形式によるクラスタ構成",
  "クラスタリング",
  "グリッドコンピューティングの説明",
  "エッジコンピューティングの説明",
  "RAID の分類",
  "RAID5 の記録方式",
  "RAID1 の外部記憶装置",
  "データ入出力の高速化",
  "RAID1~5の各構成",
  "RAID",
  "RAID に関する記述",
  "NAS の構成図",
  "NAS の特徴",
  "NAS のデータ共有を実現する単位",
  "通信の応答時間",
  "トランザクションの平均処理時間",
  "スループットに関する記述",
  "仕事量を表す用語",
  "スループットの説明",
  "トランザクションの処理能力",
  "処理できる TPS の件数",
  "スケールアウトに関する記述",
  "スケールアウトが適しているシステム",
  "ベンチマークテストの説明",
  "ベンチマークテストの説明",
  "ベンチマークに関する説明",
  "システムの信頼性に関する記述",
  "RASIS を構成する五つの要素",
  "MTBF と MTTR に関する記述",
  "MTBF",
  "MTBF と MTTR",
  "MTBF の計算",
  "稼働率の改善",
  "装置を二つ直列に接続した稼働率",
  "稼働率の差",
  "稼働率を表す計算式",
  "回線の稼働率 説明文の例題",
  "システム全体の稼働率",
  "稼働率に関する記述",
  "稼働率が最も高いシステム構成",
  "通信回線の稼働率",
  "稼働率の計算",
  "稼働率",
  "稼働率の計算",
  "稼働率の計算",
  "稼働率",
  "稼働率の計算",
  "稼働率を測定するのに適切な時期",
  "稼働率が大きくなるもの",
  "故障面からのライフサイクル",
  "故障が発生する割合",
  "縮退運転になる場合"
];
let dataList = [
  "H28 秋 13",
  "H29 秋 26",
  "H21 秋 14",
  "H21 春 31",
  "H19 春 31",
  "H27 秋 13",
  "H22 春 14",
  "R02 免 25",
  "H27 春 27",
  "H30 春 35",
  "H24 春 09",
  "H18 秋 38",
  "H19 春 38",
  "H30 春 13",
  "H28 秋 46",
  "H25 秋 13",
  "H25 春 14",
  "R03 免 15",
  "H27 秋 56",
  "H26 春 15",
  "H23 秋 17",
  "H18 春 33",
  "H23 春 15",
  "H16 秋 33",
  "H31 春 13",
  "H29 秋 13",
  "H20 春 31",
  "H30 春 14",
  "H28 秋 14",
  "H21 秋 15",
  "H26 秋 13",
  "H19 秋 35",
  "H29 秋 14",
  "H24 春 15",
  "R 元秋 72",
  "H28 春 41",
  "H24 秋 63",
  "H29 春 63",
  "H23 秋 16",
  "H28 秋 14",
  "H15 春 37",
  "H20 秋 31",
  "R05 免 04",
  "R 元秋 15",
  "H29 秋 12",
  "H29 春 11",
  "H28 秋 12",
  "H21 春 13",
  "H16 春 23",
  "H15 春 26",
  "H22 秋 15",
  "H19 春 32",
  "H17 春 24",
  "H22 春 34",
  "H21 秋 17",
  "H26 春 14",
  "H25 春 16",
  "H20 秋 33",
  "H25 秋 09",
  "H23 春 19",
  "H30 春 15",
  "H29 春 12",
  "H29 春 13",
  "H25 秋 16",
  "H19 秋 32",
  "H27 春 16",
  "H20 春 34",
  "H27 秋 14",
  "H25 秋 14",
  "H20 秋 34",
  "H16 秋 38",
  "R07免 04",
  "H29 秋 15",
  "R 元秋 16",
  "H31 春 14",
  "H30 秋 15",
  "H29 春 14",
  "H28 春 15",
  "H27 春 15",
  "H26 秋 14",
  "H24 秋 15",
  "H24 春 17",
  "H23 春 16",
  "H22 秋 19",
  "H22 春 16",
  "H21 秋 16",
  "H21 春 56",
  "H18 秋 33",
  "H26 秋 15",
  "H20 春 33",
  "H27 春 13"
];



let number = 1;
denominator.textContent = titleList.length
titleV.textContent = titleList[number-1];
data.textContent = dataList[number-1];
start.setAttribute('href', URLLlist[number-1]);

left.onclick = () =>{
    if (number > 1) {
        number--;
        numerator.textContent = number;
        titleV.textContent = titleList[number-1];
        data.textContent = dataList[number-1];
        start.setAttribute('href', URLLlist[number-1]);
    }
}
right.onclick = () =>{
    if (number < denominator.textContent) {
        number++;
        numerator.textContent = number;
        titleV.textContent = titleList[number-1];
        data.textContent = dataList[number-1];
        start.setAttribute('href', URLLlist[number-1]);
    }
}

