const titleV = document.getElementById("titleV1");
const data = document.getElementById("data1");
const left = document.getElementById("left1");
const right = document.getElementById("right1");
const start = document.getElementById("start1");
const numerator = document.getElementById("numerator1");
const denominator = document.getElementById("denominator1");

let URLlist = [
  "https://www.fe-siken.com/kakomon/23_toku/q22.html",
  "https://www.ap-siken.com/kakomon/21_aki/q18.html",
  "https://www.ap-siken.com/kakomon/31_haru/q17.html",
  "https://www.ap-siken.com/kakomon/27_aki/q11.html",
  "https://www.ap-siken.com/kakomon/21_haru/q74.html",
  "https://www.fe-siken.com/kakomon/24_haru/q24.html",
  "https://www.ap-siken.com/kakomon/17_haru/q27.html",
  "https://www.fe-siken.com/kakomon/05_menjo/q13.html",
  "https://www.ap-siken.com/kakomon/30_aki/q17.html",
  "https://www.ap-siken.com/kakomon/27_haru/q17.html",
  "https://www.ap-siken.com/kakomon/18_haru/q29.html",
  "https://www.ap-siken.com/kakomon/15_haru/q33.html",
  "https://www.ap-siken.com/kakomon/05_menjo/q13.html",
  "https://www.fe-siken.com/kakomon/24_haru/q20.html",
  "https://www.ap-siken.com/kakomon/29_haru/q16.html",
  "https://www.ap-siken.com/kakomon/28_haru/q17.html",
  "https://www.fe-siken.com/kakomon/01_aki/q17.html",
  "https://www.fe-siken.com/kakomon/01_aki/q18.html",
  "https://www.ap-siken.com/kakomon/30_aki/q16.html",
  "https://www.fe-siken.com/kakomon/01_aki/q18.html",
  "https://www.ap-siken.com/kakomon/31_haru/q16.html",
  "https://www.ap-siken.com/kakomon/30_haru/q16.html",
  "https://www.ap-siken.com/kakomon/30_aki/q18.html",
  "https://www.ap-siken.com/kakomon/28_aki/q18.html",
  "https://www.fe-siken.com/kakomon/28_haru/q16.html",
  "https://www.ap-siken.com/kakomon/27_haru/q19.html",
  "https://www.ap-siken.com/kakomon/26_haru/q16.html",
  "https://www.ap-siken.com/kakomon/24_aki/q17.html",
  "https://www.ap-siken.com/kakomon/23_haru/q18.html",
  "https://www.ap-siken.com/kakomon/29_haru/q19.html",
  "https://www.ap-siken.com/kakomon/27_aki/q17.html",
  "https://www.ap-siken.com/kakomon/29_aki/q20.html",
  "https://www.ap-siken.com/kakomon/29_haru/q15.html",
  "https://www.fe-siken.com/kakomon/04_menjo/q17.html",
  "https://www.fe-siken.com/kakomon/04_menjo/q18.html",
  "https://www.ap-siken.com/kakomon/27_haru/q20.html",
  "https://www.ap-siken.com/kakomon/26_haru/q16.html",
  "https://www.fe-siken.com/kakomon/03_menjo/q19.html",
  "https://www.ap-siken.com/kakomon/25_haru/q19.html",
  "https://www.ap-siken.com/kakomon/24_aki/q18.html",
  "https://www.ap-siken.com/kakomon/22_aki/q21.html",
  "https://www.ap-siken.com/kakomon/15_haru/q30.html",
  "https://www.ap-siken.com/kakomon/29_aki/q16.html",
  "https://www.ap-siken.com/kakomon/29_aki/q19.html",
  "https://www.fe-siken.com/kakomon/02_menjo/q17.html",
  "https://www.ap-siken.com/kakomon/21_aki/q05.html",
  "https://www.fe-siken.com/kakomon/05_menjo/q10.html",
  "https://www.ap-siken.com/kakomon/24_aki/q11.html",
  "https://www.ap-siken.com/kakomon/22_haru/q21.html",
  "https://www.ap-siken.com/kakomon/21_aki/q19.html",
  "https://www.ap-siken.com/kakomon/21_haru/q21.html",
  "https://www.ap-siken.com/kakomon/30_haru/q17.html",
  "https://www.ap-siken.com/kakomon/29_haru/q18.html",
  "https://www.ap-siken.com/kakomon/27_haru/q44.html",
  "https://www.fe-siken.com/kakomon/01_aki/q19.html",
  "https://www.ap-siken.com/kakomon/18_haru/q47.html",
  "https://www.ap-siken.com/kakomon/20_haru/q30.html",
  "https://www.ap-siken.com/kakomon/21_haru/q22.html",
  "https://www.ap-siken.com/kakomon/30_aki/q19.html",
  "https://www.ap-siken.com/kakomon/19_aki/q40.html",
  "https://www.ap-siken.com/kakomon/17_aki/q36.html",
  "https://www.ap-siken.com/kakomon/30_aki/q20.html",
  "https://www.ap-siken.com/kakomon/24_aki/q20.html",
  "https://www.ap-siken.com/kakomon/31_haru/q19.html",
  "https://www.fe-siken.com/kakomon/23_toku/q23.html",
  "https://www.ap-siken.com/kakomon/30_haru/q18.html",
  "https://www.ap-siken.com/kakomon/28_haru/q19.html",
  "https://www.ap-siken.com/kakomon/31_haru/q48.html",
  "https://www.ap-siken.com/kakomon/28_haru/q21.html",
  "https://www.ap-siken.com/kakomon/27_aki/q20.html",
  "https://www.ap-siken.com/kakomon/22_aki/q23.html",
  "https://www.fe-siken.com/kakomon/01_aki/q48.html",
  "https://www.ap-siken.com/kakomon/25_haru/q47.html",
  "https://www.ap-siken.com/kakomon/30_haru/q19.html",
  "https://www.ap-siken.com/kakomon/27_aki/q20.html",
  "https://www.ap-siken.com/kakomon/26_aki/q20.html",
  "https://www.ap-siken.com/kakomon/30_haru/q20.html",
  "https://www.ap-siken.com/kakomon/30_haru/q26.html"
];
let titleList = [
"リアルタイムＯＳ",
"リアルタイムＯＳ",
"デバイスドライバ",
"デバイスドライバの役割",
"組込みシステムの用途",
"シェルのリダイレクト機能",
"OS におけるシェルの役割",
"ジョブ終了までの経過時間",
"スプーリング",
"スプーリング",
"スプールファイルの全容量",
"スプーリングファイルの容量",
"ジョブ終了までの経過時間",
"ジョブの終了までの時間",
"JOB 処理時間",
"入出力管理におけるバッファの機能",
"バッファサイズ L を表す関係式",
"タスクスケジューリング",
"マルチプログラミング",
"スケジューリング・リアルタイム OS",
"タスクのディスパッチ",
"タスクスケジューリング",
"タスクスケジューリング（ラウンドロビン方式）",
"マルチプログラミング OS の処理",
"プリエンティブナスケジューリング",
"タスクスケジューリング方式（ノンプリエンティブ）",
"タスクスジェジュール（プリエンティブ）",
"タスクスケジューリング",
"CPU 使用率",
"仮想記憶方式（FIFO,LRU)",
"仮想記憶管理のページ入替え",
"ページフォールトの原因",
"ページング方式 2",
"ページング方式（LRU)",
"LRU 方式",
"ページング方式（LRU）",
"ページング方式の仮想記憶",
"ページング方式",
"スラッシングが発生しやすい組合せ",
"細切れの未使用領域が多数",
"スラシングの発生",
"スラッシングの発生",
"メモリリーク",
"メモリアクセス時間の計算（メモリコンパクション）",
"メモリプール管理",
"スタック",
"DMA の説明",
"ファイルアクセスの高速化",
"UNIX 階層的ファイルシステム",
"カレントディレクトリィ",
"ディレクトリとファイルの指定方法",
"絶対パス",
"カレントディレクトリ",
"ファイルパーミッション",
"バックアップ方式(増分)の説明",
"差分バックアップ方式に関する記述",
"アーカイブの説明",
"コンパイラ・リンカ・ローダの組合せ",
"手続型言語のコンパイラ",
"各種言語プロセッサの説明",
"言語処理プログラム",
"リンカの機能",
"動的リンク",
"インタプリタの説明",
"インタプリタでの実行",
"コンパイラによる最適化の目的",
"最適化の説明",
"静的テストを支援する静的解析ツール",
"静的テストツールの機能",
"オープンソースの統合開発環境",
"静的解析ツールで検出できるもの",
"ドライバとスタブの機能",
"スタブを使用したテストの説明",
"OSS について 2",
"オープンソースの統合開発環境",
"オープンソースライセンス",
"大規模データの分散処理を実現する OSS",
"AR の説明"
];
let dataList = [
"H23 特 22",
"H21 秋 18",
"H31 春 17",
"H27 秋 11",
"H21 春 74",
"H24 春 24",
"H17 春 27",
"R05 免 13",
"H30 秋 17",
"H27 春 17",
"H18 春 29",
"H15 春 33",
"R05 免 13",
"H24 春 20",
"H29 春 16",
"H28 春 17",
"R 元秋 17",
"R 元秋 18",
"H30 秋 16",
"R1 秋 18",
"H31 春 16",
"H30 春 16",
"H30 秋 18",
"H28 秋 18",
"H28 春 16",
"H27 春 19",
"H26 春 16",
"H24 秋 17",
"H23 春 18",
"H29 春 19",
"H27 秋 17",
"H29 秋 20",
"H29 春 15",
"R04 免 17",
"R04 免 18",
"H27 春 20",
"H26 春 16",
"R03 免 19",
"H25 春 19",
"H24 秋１８",
"H22 秋 21",
"H15 春 30",
"H29 秋 16",
"H29 秋 19",
"R02 免 17",
"H21 秋 05",
"R05 免 10",
"H24 秋 11",
"H22 春 21",
"H21 秋 19",
"H21 春 21",
"H30 春 17",
"H29 春 18",
"H27 春 44",
"R 元秋 19",
"H18 春 47",
"H20 春 30",
"H21 春 22",
"H30 秋 19",
"H19 秋 40",
"H17 秋 36",
"H30 秋 20",
"H24 秋 20",
"H31 春 19",
"H23 特 23",
"H30 春 18",
"H28 春 19",
"H31 春 48",
"H28 春 21",
"H27 秋 20",
"H22 秋 23",
"R 元秋 48",
"H25 春 47",
"H30 春 19",
"H27 秋 20",
"H26 秋 20",
"H30 春 20",
"H30 春 26"
];



let number = 1;
denominator.textContent = titleList.length
titleV.textContent = titleList[number-1];
data.textContent = dataList[number-1];
start.setAttribute('href', URLlist[number-1]);

left.onclick = () =>{
    if (number > 1) {
        number--;
        numerator.textContent = number;
        titleV.textContent = titleList[number-1];
        data.textContent = dataList[number-1];
        start.setAttribute('href', URLlist[number-1]);
    }
}
right.onclick = () =>{
    if (number < denominator.textContent) {
        number++;
        numerator.textContent = number;
        titleV.textContent = titleList[number-1];
        data.textContent = dataList[number-1];
        start.setAttribute('href', URLlist[number-1]);
    }
}

